### ISSUE TITLE
有路由的封装示例吗

### ISSUE THREAD

**Issue by JamesGZM** [CalmHarbin/uniApp-template#1]

**Comment by JamesGZM** [comment]
我试了一下 vue-router 在微信小程序是用不了的 我的意思是兼容uni的路由

**Comment by CalmHarbin** [comment]
> 我试了一下 vue-router 在微信小程序是用不了的 我的意思是兼容uni的路由

为什么在uni-app中还需要使用vue-router了？框架本身就已经支持路由功能了，你可以直接使用。
